-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Main events table
create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- User identification
  user_id uuid, -- Can link to auth.users if needed
  anonymous_id text, -- Required for tracking unauthenticated users
  session_id text, -- To group events into sessions
  
  -- Event details
  event_type text not null, -- e.g., 'page_view', 'pdf_read', 'feature_usage', 'interaction'
  
  -- Data payload
  -- Stores specific details like:
  -- pdf_read: { "pdfId": "...", "duration": 120, "pages": 5 }
  -- feature_usage: { "feature": "reading_mode", "value": "on" }
  -- location: { "country": "US", "city": "New York" } (if passed from client)
  event_data jsonb default '{}'::jsonb, 
  
  -- Context
  url text,
  referrer text,
  user_agent text,
  ip_address text,
  
  -- Client timestamp (when the event actually happened on client)
  client_timestamp timestamp with time zone
);

-- Indexes for performance on common query patterns
create index if not exists idx_analytics_events_user_id on analytics_events(user_id);
create index if not exists idx_analytics_events_anonymous_id on analytics_events(anonymous_id);
create index if not exists idx_analytics_events_event_type on analytics_events(event_type);
create index if not exists idx_analytics_events_created_at on analytics_events(created_at);
create index if not exists idx_analytics_events_event_data on analytics_events using gin (event_data);

-- Row Level Security (RLS)
alter table analytics_events enable row level security;

-- Policy: Allow anyone (anon) to insert data
create policy "Enable insert for all users" 
on analytics_events 
for insert 
with check (true);

-- Policy: Only allow service_role (backend/admin) to view data
-- This prevents public users from querying the analytics data
create policy "Enable read access for service role only" 
on analytics_events 
for select 
using (auth.role() = 'service_role');

-- Comments for documentation
comment on table analytics_events is 'Stores all user interaction and analytics events';
comment on column analytics_events.user_id is 'Supabase Auth User ID if logged in';
comment on column analytics_events.anonymous_id is 'Client-generated ID for tracking guest users';
comment on column analytics_events.event_data is 'JSONB column containing event-specific properties (duration, metadata, etc.)';
